# Generated by Django 4.0.5 on 2022-08-01 16:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Clubs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=120)),
                ('prezident', models.CharField(max_length=120)),
                ('murabbiy', models.CharField(max_length=130)),
                ('yoshi', models.DateField()),
                ('max_sotib_olingan', models.SmallIntegerField()),
                ('max_sotilgan', models.SmallIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Transfer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=150)),
                ('qaysi_clubdan', models.CharField(max_length=30)),
                ('qaysi_clubga', models.CharField(max_length=30)),
                ('tahminiy_narxi', models.SmallIntegerField()),
                ('haqiqiy_narxi', models.SmallIntegerField()),
                ('sezon', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Oyinchilar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ism', models.CharField(max_length=120)),
                ('yosh', models.SmallIntegerField()),
                ('davlat', models.CharField(max_length=130)),
                ('pozitsiya', models.CharField(max_length=120)),
                ('haqiqiy_transfer_narxi', models.SmallIntegerField(null=True)),
                ('tahminiy_transfer_narxi', models.SmallIntegerField()),
                ('club', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.clubs')),
            ],
        ),
    ]
