# Generated by Django 4.0.5 on 2022-08-02 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='clubs',
            name='davlat',
            field=models.CharField(blank=True, max_length=120),
        ),
    ]
