# Generated by Django 4.0.5 on 2022-08-05 08:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0003_davlat'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Davlat',
        ),
    ]
